# Generated by Django 3.1.5 on 2021-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_id',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
